packages:
  - packages/*
  - fixtures/*
autoInstallPeers: false
allowBuilds:
  esbuild: true
  libxmljs2: true
engineStrict: true
minimumReleaseAgeExclude:
  - tsx@4.23.11
saveExact: true
sharedWorkspaceLockfile: true
storeDir: .pnpm-store
strictPeerDependencies: true
